# Generated by Django 2.2.9 on 2020-01-31 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GenreModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Жанр')),
            ],
        ),
        migrations.CreateModel(
            name='AnimeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Название Аниме')),
                ('title_orig', models.CharField(max_length=120, verbose_name='Оригинальное название Аниме')),
                ('text', models.TextField(verbose_name='Описание')),
                ('date', models.DateField(verbose_name='Дата выпуска')),
                ('info', models.TextField(verbose_name='Прочая информация')),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение 300x450')),
                ('classification', models.CharField(choices=[(0, 'Для всех'), (12, 'Для лиц старше 12 лет'), (16, 'Для лиц старше 16 лет'), (18, 'Для лиц старше 18 лет')], default=(0, 'Для всех'), max_length=50)),
                ('genre', models.ManyToManyField(related_name='genre', to='Posts.GenreModel')),
            ],
        ),
    ]
