# Generated by Django 2.2.9 on 2020-01-31 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animemodel',
            name='classification',
        ),
        migrations.RemoveField(
            model_name='animemodel',
            name='info',
        ),
        migrations.RemoveField(
            model_name='animemodel',
            name='text',
        ),
        migrations.RemoveField(
            model_name='animemodel',
            name='title_orig',
        ),
        migrations.AddField(
            model_name='animemodel',
            name='author',
            field=models.CharField(default=None, max_length=120, verbose_name='Автор оригинала/Сценарист'),
        ),
        migrations.AddField(
            model_name='animemodel',
            name='country',
            field=models.CharField(default=None, max_length=120, verbose_name='Страна'),
        ),
        migrations.AddField(
            model_name='animemodel',
            name='description',
            field=models.TextField(default=None, max_length=10240, verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='animemodel',
            name='director',
            field=models.CharField(default=None, max_length=120, verbose_name='Режиссер'),
        ),
        migrations.AddField(
            model_name='animemodel',
            name='episodes',
            field=models.IntegerField(default=None, verbose_name='Количество серий'),
        ),
        migrations.AddField(
            model_name='animemodel',
            name='sound',
            field=models.CharField(default=None, max_length=120, verbose_name='Озвучивание'),
        ),
        migrations.AddField(
            model_name='animemodel',
            name='studio',
            field=models.CharField(default=None, max_length=120, verbose_name='Студия'),
        ),
        migrations.AddField(
            model_name='animemodel',
            name='translate',
            field=models.CharField(default=None, max_length=120, verbose_name='Перевод'),
        ),
        migrations.AddField(
            model_name='animemodel',
            name='year',
            field=models.IntegerField(default=None, verbose_name='Год'),
        ),
        migrations.AlterField(
            model_name='animemodel',
            name='date',
            field=models.CharField(default=None, max_length=120, verbose_name='Дата выпуска'),
        ),
        migrations.AlterField(
            model_name='animemodel',
            name='genre',
            field=models.ManyToManyField(default=None, related_name='anime', to='Posts.GenreModel', verbose_name='Жанр'),
        ),
        migrations.AlterField(
            model_name='animemodel',
            name='image',
            field=models.URLField(verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='animemodel',
            name='title',
            field=models.CharField(max_length=240, verbose_name='Название аниме'),
        ),
    ]
