# Generated by Django 2.2.9 on 2020-01-31 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0002_auto_20200131_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animemodel',
            name='author',
            field=models.CharField(default=None, max_length=240, verbose_name='Автор оригинала/Сценарист'),
        ),
        migrations.AlterField(
            model_name='animemodel',
            name='country',
            field=models.CharField(default=None, max_length=240, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='animemodel',
            name='date',
            field=models.CharField(default=None, max_length=240, verbose_name='Дата выпуска'),
        ),
        migrations.AlterField(
            model_name='animemodel',
            name='description',
            field=models.TextField(blank=True, max_length=10240, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='animemodel',
            name='director',
            field=models.CharField(default=None, max_length=240, verbose_name='Режиссер'),
        ),
        migrations.AlterField(
            model_name='animemodel',
            name='sound',
            field=models.CharField(default=None, max_length=240, verbose_name='Озвучивание'),
        ),
        migrations.AlterField(
            model_name='animemodel',
            name='studio',
            field=models.CharField(default=None, max_length=240, verbose_name='Студия'),
        ),
        migrations.AlterField(
            model_name='animemodel',
            name='translate',
            field=models.CharField(default=None, max_length=240, verbose_name='Перевод'),
        ),
        migrations.AlterField(
            model_name='genremodel',
            name='title',
            field=models.CharField(max_length=240, verbose_name='Жанр'),
        ),
    ]
