# Generated by Django 2.2.9 on 2020-02-01 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0003_auto_20200131_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animemodel',
            name='genre',
            field=models.ManyToManyField(blank=True, related_name='anime', to='Posts.GenreModel', verbose_name='Жанр'),
        ),
    ]
