# Generated by Django 2.2.9 on 2020-02-01 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0004_auto_20200201_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animemodel',
            name='author',
            field=models.CharField(blank=True, max_length=240, verbose_name='Автор оригинала/Сценарист'),
        ),
        migrations.AlterField(
            model_name='animemodel',
            name='country',
            field=models.CharField(blank=True, max_length=240, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='animemodel',
            name='date',
            field=models.CharField(blank=True, max_length=240, verbose_name='Дата выпуска'),
        ),
        migrations.AlterField(
            model_name='animemodel',
            name='director',
            field=models.CharField(blank=True, max_length=240, verbose_name='Режиссер'),
        ),
        migrations.AlterField(
            model_name='animemodel',
            name='episodes',
            field=models.IntegerField(blank=True, verbose_name='Количество серий'),
        ),
        migrations.AlterField(
            model_name='animemodel',
            name='sound',
            field=models.CharField(blank=True, max_length=240, verbose_name='Озвучивание'),
        ),
        migrations.AlterField(
            model_name='animemodel',
            name='studio',
            field=models.CharField(blank=True, max_length=240, verbose_name='Студия'),
        ),
        migrations.AlterField(
            model_name='animemodel',
            name='translate',
            field=models.CharField(blank=True, max_length=240, verbose_name='Перевод'),
        ),
        migrations.AlterField(
            model_name='animemodel',
            name='year',
            field=models.IntegerField(blank=True, verbose_name='Год'),
        ),
    ]
